# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Awayzone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awayzone
    pod 'IQKeyboardManagerSwift', '~> 5.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'TwitterKit'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    
target 'AwayzoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwayzoneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
